# -*- coding: utf-8 -*-
"""
📜 verify_data_loader.py
────────────────────────────────────────────────────────────────────────────────
WM-811K Data Verification Script

### 🎯 PURPOSE
This script performs a sanity check on the `.npz` file generated by Stage 1 
(`data_loader.py`). It ensures the data integrity before moving to Feature Engineering.

### ⚙️ CHECKS PERFORMED
1. Shape Verification: checks if dimensions match (N_samples, 64, 64).
2. Data Integrity: Ensures pixel values are strictly discrete {0, 1, 2}.
   - 0: Background/Empty
   - 1: Normal Die
   - 2: Defective Die
3. Class Distribution: Prints the count and percentage of each failure type.
4. Visualization: Plots random samples from every class to visually confirm resizing.

### 📦 INPUT
- Path to `cleaned_full_wm811k.npz`
────────────────────────────────────────────────────────────────────────────────
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

def verify_data(file_path: str):
    """
    Loads and inspects the WM-811K .npz file.

    Args:
        file_path (str): Absolute path to the .npz file.
    """
    print(f"🔍 Inspecting file: {file_path}")
    
    if not os.path.exists(file_path):
        print("❌ Error: File not found! Please run 'data_loader.py' first.")
        return

    # ──────────────────────────────────────────────────────────────────────────
    # 1. LOAD DATA & CHECK SHAPE
    # ──────────────────────────────────────────────────────────────────────────
    try:
        data = np.load(file_path)
        X = data['waferMap']
        y = data['labels']
    except KeyError as e:
        print(f"❌ Error: Missing key in NPZ file: {e}")
        return

    print("\n" + "="*40)
    print("📊 1. DIMENSION CHECK")
    print("="*40)
    print(f"✅ Wafer Map Shape: {X.shape}")
    print(f"   (Expected: ~172k samples, 64x64 resolution)")
    print(f"✅ Labels Shape:    {y.shape}")
    
    # ──────────────────────────────────────────────────────────────────────────
    # 2. DATA INTEGRITY CHECK
    # ──────────────────────────────────────────────────────────────────────────
    print("\n" + "="*40)
    print("DATA INTEGRITY CHECK")
    print("="*40)
    
    unique_vals = np.unique(X)
    print(f"Unique pixel values found: {unique_vals}")
    
    # Check if all values are integers within standard wafer map set {0, 1, 2}
    expected_values = {0, 1, 2}
    if set(unique_vals).issubset(expected_values):
        print("✅ PASS: Data contains only discrete values (0, 1, 2).")
        print("   (0=Background, 1=Good Die, 2=Defect)")
    else:
        print(f"⚠️ WARNING: Found unexpected values: {unique_vals}")
        print("   Did resizing use interpolation (bilinear/bicubic)? It should use Nearest Neighbor.")

    # ──────────────────────────────────────────────────────────────────────────
    # 3. CLASS DISTRIBUTION
    # ──────────────────────────────────────────────────────────────────────────
    print("\n" + "="*40)
    print("📈 3. CLASS DISTRIBUTION")
    print("="*40)
    
    mapping_rev = {
        0: "Center", 1: "Donut", 2: "Edge-Loc", 3: "Edge-Ring",
        4: "Loc", 5: "Random", 6: "Scratch", 7: "none"
    }
    
    unique, counts = np.unique(y, return_counts=True)
    total_samples = len(y)
    
    # Print Header
    print(f"{'ID':<5} {'Class Name':<15} {'Count':<10} {'Percentage':<10}")
    print("-" * 50)
    
    for label, count in zip(unique, counts):
        name = mapping_rev.get(label, "Unknown")
        pct = (count / total_samples) * 100
        print(f"{label:<5} {name:<15} {count:<10} {pct:.2f}%")

    # ──────────────────────────────────────────────────────────────────────────
    # 4. VISUALIZATION
    # ──────────────────────────────────────────────────────────────────────────
    print("\n" + "="*40)
    print("🖼️ 4. VISUALIZATION CHECK")
    print("="*40)

    rng = np.random.default_rng(42)
    available_classes = [c for c in sorted(mapping_rev.keys()) if np.any(y == c)]
    num_classes = len(available_classes)

    print(f"Displaying 1 random sample for each of the {num_classes} classes...")

    cols = 4
    rows = int(np.ceil(num_classes / cols))
    
    fig, axes = plt.subplots(rows, cols, figsize=(16, 4 * rows))
    axes = axes.flatten()

    # --- CUSTOM COLORMAP ---
    # 0 = White (Background), 1 = Light Gray (Good Die), 2 = Red (Defect)
    colors = ['#ffffff', '#e0e0e0', '#d62728'] 
    cmap = ListedColormap(colors)

    for i, ax in enumerate(axes):
        if i < num_classes:
            cls = available_classes[i]
            indices = np.where(y == cls)[0]
            
            # Pick a random image from this class
            idx = rng.choice(indices)
            img = X[idx]

            ax.imshow(img, cmap=cmap, vmin=0, vmax=2)
            ax.set_title(f"{mapping_rev[cls]} (ID: {cls})", fontsize=12, fontweight='bold')
            ax.axis("on")
            # Add a border to see the image boundaries clearly
            for spine in ax.spines.values():
                spine.set_edgecolor('#ccc')
        else:
            # Hide unused subplots
            ax.axis("off")

    plt.suptitle("Wafer Map Samples (Verification Step)", fontsize=16, y=0.98)
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    # --- CONFIGURATION ---
    # Ensure this path matches the output from data_loader.py
    FILE_PATH = r"C:\Users\user\OneDrive - ums.edu.my\FYP 1\data_loader_results\cleaned_full_wm811k.npz"
    
    verify_data(FILE_PATH)